# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/MTCNN_CONVERT2/detection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/MTCNN_CONVERT2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"python\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/MTCNN_CONVERT2/CMakeFiles /home/dev/MTCNN_CONVERT2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/MTCNN_CONVERT2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pbcvt

# Build rule for target.
pbcvt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbcvt
.PHONY : pbcvt

# fast build rule for target.
pbcvt/fast:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/build
.PHONY : pbcvt/fast

MTCNN.o: MTCNN.cpp.o

.PHONY : MTCNN.o

# target to build an object file
MTCNN.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/MTCNN.cpp.o
.PHONY : MTCNN.cpp.o

MTCNN.i: MTCNN.cpp.i

.PHONY : MTCNN.i

# target to preprocess a source file
MTCNN.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/MTCNN.cpp.i
.PHONY : MTCNN.cpp.i

MTCNN.s: MTCNN.cpp.s

.PHONY : MTCNN.s

# target to generate assembly for a file
MTCNN.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/MTCNN.cpp.s
.PHONY : MTCNN.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/main.cpp.s
.PHONY : main.cpp.s

posface.o: posface.cpp.o

.PHONY : posface.o

# target to build an object file
posface.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/posface.cpp.o
.PHONY : posface.cpp.o

posface.i: posface.cpp.i

.PHONY : posface.i

# target to preprocess a source file
posface.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/posface.cpp.i
.PHONY : posface.cpp.i

posface.s: posface.cpp.s

.PHONY : posface.s

# target to generate assembly for a file
posface.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/posface.cpp.s
.PHONY : posface.cpp.s

pyboost_cv2_converter.o: pyboost_cv2_converter.cpp.o

.PHONY : pyboost_cv2_converter.o

# target to build an object file
pyboost_cv2_converter.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/pyboost_cv2_converter.cpp.o
.PHONY : pyboost_cv2_converter.cpp.o

pyboost_cv2_converter.i: pyboost_cv2_converter.cpp.i

.PHONY : pyboost_cv2_converter.i

# target to preprocess a source file
pyboost_cv2_converter.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/pyboost_cv2_converter.cpp.i
.PHONY : pyboost_cv2_converter.cpp.i

pyboost_cv2_converter.s: pyboost_cv2_converter.cpp.s

.PHONY : pyboost_cv2_converter.s

# target to generate assembly for a file
pyboost_cv2_converter.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/pyboost_cv2_converter.cpp.s
.PHONY : pyboost_cv2_converter.cpp.s

pyboost_cv3_converter.o: pyboost_cv3_converter.cpp.o

.PHONY : pyboost_cv3_converter.o

# target to build an object file
pyboost_cv3_converter.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/pyboost_cv3_converter.cpp.o
.PHONY : pyboost_cv3_converter.cpp.o

pyboost_cv3_converter.i: pyboost_cv3_converter.cpp.i

.PHONY : pyboost_cv3_converter.i

# target to preprocess a source file
pyboost_cv3_converter.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/pyboost_cv3_converter.cpp.i
.PHONY : pyboost_cv3_converter.cpp.i

pyboost_cv3_converter.s: pyboost_cv3_converter.cpp.s

.PHONY : pyboost_cv3_converter.s

# target to generate assembly for a file
pyboost_cv3_converter.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/pyboost_cv3_converter.cpp.s
.PHONY : pyboost_cv3_converter.cpp.s

python_module.o: python_module.cpp.o

.PHONY : python_module.o

# target to build an object file
python_module.cpp.o:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/python_module.cpp.o
.PHONY : python_module.cpp.o

python_module.i: python_module.cpp.i

.PHONY : python_module.i

# target to preprocess a source file
python_module.cpp.i:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/python_module.cpp.i
.PHONY : python_module.cpp.i

python_module.s: python_module.cpp.s

.PHONY : python_module.s

# target to generate assembly for a file
python_module.cpp.s:
	$(MAKE) -f CMakeFiles/pbcvt.dir/build.make CMakeFiles/pbcvt.dir/python_module.cpp.s
.PHONY : python_module.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... pbcvt"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... MTCNN.o"
	@echo "... MTCNN.i"
	@echo "... MTCNN.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... posface.o"
	@echo "... posface.i"
	@echo "... posface.s"
	@echo "... pyboost_cv2_converter.o"
	@echo "... pyboost_cv2_converter.i"
	@echo "... pyboost_cv2_converter.s"
	@echo "... pyboost_cv3_converter.o"
	@echo "... pyboost_cv3_converter.i"
	@echo "... pyboost_cv3_converter.s"
	@echo "... python_module.o"
	@echo "... python_module.i"
	@echo "... python_module.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

